#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>CGI Bash</title>"
echo "<link rel='stylesheet' href='../style.css'></head><body>"
echo "<div class='container'>"
echo "<header><h1>Bash CGI Test</h1><p class='subtitle'>Generated dynamically by Bash</p></header>"
echo "<nav><a href='../index.html'>Dashboard</a><a href='../cgi.html'>CGI Tests</a></nav>"
echo "<div class='card'>"
echo "<h2>Hello from Bash! 🐚</h2>"
echo "<ul>"
echo "<li><strong>Server Name:</strong> $SERVER_NAME</li>"
echo "<li><strong>Request Method:</strong> $REQUEST_METHOD</li>"
echo "<li><strong>Server Protocol:</strong> $SERVER_PROTOCOL</li>"
echo "</ul>"
echo "</div>"
echo "<footer><p>WebServ Project &copy; 2026</p></footer>"
echo "</div></body></html>"
