#!/usr/bin/env python3
import time

print("Content-Type: text/html\r\n\r\n")
print("<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>CGI Python</title>")
print("<link rel='stylesheet' href='../style.css'></head><body>")
print("<div class='container'>")
print("<header><h1>Python CGI Test</h1><p class='subtitle'>Generated dynamically by Python</p></header>")
print("<nav><a href='../index.html'>Dashboard</a><a href='../cgi.html'>CGI Tests</a></nav>")
print("<div class='card'>")
print("<h2>Hello from Python! 🐍</h2>")
print("<p>This page was generated by a Python script running on the server.</p>")
print("<p>Current Server Time: <strong>" + time.ctime() + "</strong></p>")
print("</div>")
print("<footer><p>WebServ Project &copy; 2026</p></footer>")
print("</div></body></html>")
